#! /bin/sh

sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX

bspc config border_width                  1
bspc config normal_border_color           "#555555"
bspc config focused_border_color          "$COLOR_HIGHLIGHT"
bspc config window_gap                    10
bspc config top_padding                   5
bspc config bottom_padding                45
bspc config single_monocle                false
bspc config borderless_monocle            true
bspc config gapless_monocle               false
bspc config pointer_follows_monitor       true
bspc config focus_follows_pointer         true
bspc config click_to_focus                true
bspc config presel_feedback_color         "$COLOR_HIGHLIGHT"
bspc config split_ratio          0.6

bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a plasmashell manage=off 
bspc rule -a Plasma manage=off
bspc rule -a plasma-desktop manage=off
bspc rule -a python3 state=floating
bspc rule -a yakuake state=floating

feh home/arseny/Pictures/2d3d52493e0d9b7552b5bf0cf567f44d.jpg --bg-scale
eval $(ssh-agent -s)

compton --config "$HOME/.config/compton.conf" -b
polybar top
