#! /bin/sh

sxhkd &

xrandr | grep VGA-1 | grep -v disconnected && xrandr --output VGA-1 --primary --auto --right-of LVDS-1 --auto
#bspc monitor -d I II III IV V VI VII VIII IX 
bspc monitor VGA-1 -d I II III IV V 
bspc monitor LVDS-1 -d VI VII VIII IX 

bspc config border_width			1
bspc config window_gap				10
bspc config top_padding				3

bspc config split_ratio				0.60
bspc config borderless_monocle		true
bspc config gapless_monocle			false
bspc config focus_follows_pointer	true

bspc config normal_border_color		"#3c3836"
bspc config focused_border_color	"#665c54"
bspc config presel_feedback_color	"#7c6f64"

compton --config "home/arseny/.config/compton.conf" -b
setxkbmap -layout 'us,ru' -option 'grp:caps_toggle,grp_led:caps'
eval $(ssh-agent -s)
sh ~/.scripts/.fehbg

polybar primary &
xrandr | grep VGA-1 | grep -v disconnected && polybar secondary &
