#! /bin/sh

sxhkd &
kbdd &

xrandr --output DP-1 --auto --rotate left --left-of DP-2
xrandr --output DP-2 --pos 1440x600
#bspc monitor -d I II III IV V VI VII VIII IX 
bspc monitor DP-1 -d I II III IV V 
bspc monitor DP-2 -d VI VII VIII IX X

bspc config border_width			0
bspc config window_gap				20
bspc config top_padding				3

bspc config split_ratio				0.60
bspc config borderless_monocle		true
bspc config gapless_monocle			false
bspc config focus_follows_pointer	true

bspc config normal_border_color		"#3c3836"
bspc config focused_border_color	"#665c54"
bspc config presel_feedback_color	"#7c6f64"

bspc rule -a '*:zathura' state=tiled desktop=^3 follow=on
bspc rule -a '*:telegram-desktop' state=tiled desktop=^5
bspc rula -a feh state=floating

compton --config $HOME/.config/compton.conf -b
# setxkbmap -option caps:swapescape
setxkbmap -layout 'us,ru' -option 'grp:caps_toggle,grp_led:caps'
eval $(ssh-agent -s)
sh ~/.scripts/fehbg

polybar primary &
polybar secondary &
