#! /bin/sh

$HOME/.config/bspwm/autostart

xsetroot -cursor_name left_ptr

xrandr --output DP-6 --auto --rotate left --right-of DP-1
xrandr --output DP-4 --auto --rotate left --left-of DP-1
xrandr --output DP-1 --pos 1440x600 --primary

bspc monitor DP-4 -d 1 2 3 4 5
bspc monitor DP-7 -d 6 7 8 9 0
bspc monitor DP-0 -d 11 12 13 14 15

bspc config border_width			0
bspc config window_gap				20
bspc config top_padding				3

bspc config split_ratio				0.50
bspc config borderless_monocle		true
bspc config gapless_monocle			false
bspc config focus_follows_pointer	true

bspc config normal_border_color		"#3c3836"
bspc config focused_border_color	"#665c54"
bspc config presel_feedback_color	"#7c6f64"

bspc rule -a '*:zathura' state=tiled desktop=^3 follow=on
bspc rule -a '*:telegram-desktop' state=tiled desktop=^5
bspc rula -a feh state=floating

compton --config $HOME/.config/compton.conf -b
# setxkbmap -option caps:swapescape
# setxkbmap -layout 'us,ru' -option 'grp:caps_toggle,grp_led:caps'
# xmodmap ~/.Xmodmap
# setxkbmap -layout "us,ru" -option "grp:escape,grp_led:caps"

eval $(ssh-agent -s)
sh /home/azorin/.scripts/fehbg
