#! /bin/sh

$HOME/.config/bspwm/autostart

xsetroot -cursor_name left_ptr

xrandr --output DP-5 --auto --rotate left --left-of DP-6
xrandr --output DP-6 --pos 1440x0 --primary

bspc monitor DP-5 -d 1 2 3 4
bspc monitor DP-6 -d 5 6 7 8

bspc config border_width			0
bspc config window_gap				20
bspc config top_padding				3

bspc config split_ratio				0.50
bspc config borderless_monocle		true
bspc config gapless_monocle			false
bspc config focus_follows_pointer	true

bspc config normal_border_color		"#3c3836"
bspc config focused_border_color	"#665c54"
bspc config presel_feedback_color	"#7c6f64"

bspc rule -a '*:zathura' state=tiled desktop=^3 follow=on
bspc rula -a feh state=floating

compton --config $HOME/.config/compton.conf -b

eval $(ssh-agent -s)
sh $HOME/.scripts/fehbg
