#!/bin/zsh
empty_icon=""
filled_icon=""
focused_icon=""

notification=""
focused=$(bspc query -T -d | jq  '.name' | sed -r 's/("|")//g')
for row in {1..3}; do
	for col in {1..5}; do
		sub=$(( $row - 1 ))
		mult=$(( 3 * $sub ))
		res=$(( $mult + $col ))
		cell=$empty_icon
		if [[ $res == $focused ]]; then
			cell=$focused_icon
		elif [[ -n $(bspc query -N -d $res) ]]; then
			cell=$filled_icon
		fi
		cell="$cell"
		if [[ $col -eq 1 ]]; then
			notification=$notification$cell
		else
			notification=$notification' '$cell
		fi
  
	done
	notification="$notification
"
done
notification=`echo $notification | sed s/'$ d'//g`
dunstify "$notification" -r 3001 -u low
