#!/bin/bash
setxkbmap us
tmp="/tmp/lock"
pic="$HOME/.wallpaper/lockscreen.png"

convert "$pic" -pointsize 30 -font 'SF-Mono-Regular' -annotate +1600+1000 "`~/.scripts/cal`" -annotate +4050+150 "`task +Work or +Siemens li`" $tmp

i3lock -i /tmp/lock
